[theme]
# Light theme by default
primaryColor = "#000000"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F5F5F5"
textColor = "#000000"
font = "sans serif"

[server]
enableXsrfProtection = false
enableCORS = false
